tunnel: zebra-print
credentials-file: C:\Users\Innovation\.cloudflared\ecbe7a67-9135-4368-8076-0dba1033d10b.json

ingress:
  - hostname: print.innovationbrindes.com.br
    service: http://localhost:4545
  - service: http_status:404